/**
 * @file storage.js
 * @description Persistent storage service for LifeLine AI.
 * Wraps localStorage with a namespaced prefix and provides typed
 * helpers for tasks, chat history, settings, and stats.
 * @module services/storage
 */

import { CONFIG } from '../config.js';

// ── Helpers ────────────────────────────────────────────────────────────

/**
 * Generate a UUID v4 string.
 * Uses crypto.randomUUID() when available, otherwise falls back to a
 * Math.random-based polyfill.
 * @returns {string} A UUID such as "f47ac10b-58cc-4372-a567-0e02b2c3d479"
 */
function generateId() {
  if (typeof crypto !== 'undefined' && crypto.randomUUID) {
    return crypto.randomUUID();
  }
  // Fallback for older browsers
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

/**
 * Build the full localStorage key by prepending the app prefix.
 * @param {string} key — Logical key name (e.g. "tasks")
 * @returns {string} Prefixed key (e.g. "lifeline_tasks")
 */
function prefixKey(key) {
  return `${CONFIG.STORAGE_PREFIX}${key}`;
}

// ── Generic CRUD ───────────────────────────────────────────────────────

/**
 * Retrieve a value from localStorage.
 * @param {string} key — Logical key (prefix is added automatically)
 * @param {*} [fallback=null] — Value returned when the key does not exist
 * @returns {*} Parsed JSON value, or `fallback`
 */
export function get(key, fallback = null) {
  try {
    const raw = localStorage.getItem(prefixKey(key));
    return raw !== null ? JSON.parse(raw) : fallback;
  } catch (err) {
    console.warn(`[Storage] Failed to read "${key}":`, err);
    return fallback;
  }
}

/**
 * Write a value to localStorage (JSON-serialised).
 * @param {string} key — Logical key
 * @param {*} value — Any JSON-serialisable value
 */
export function set(key, value) {
  try {
    localStorage.setItem(prefixKey(key), JSON.stringify(value));
  } catch (err) {
    console.error(`[Storage] Failed to write "${key}":`, err);
  }
}

/**
 * Remove a single key from localStorage.
 * @param {string} key — Logical key
 */
export function remove(key) {
  localStorage.removeItem(prefixKey(key));
}

/**
 * Remove **all** keys that belong to this application.
 */
export function clear() {
  const prefix = CONFIG.STORAGE_PREFIX;
  const keysToRemove = [];
  for (let i = 0; i < localStorage.length; i++) {
    const k = localStorage.key(i);
    if (k && k.startsWith(prefix)) {
      keysToRemove.push(k);
    }
  }
  keysToRemove.forEach((k) => localStorage.removeItem(k));
}

// ── Task helpers ───────────────────────────────────────────────────────

/**
 * @typedef {Object} Subtask
 * @property {string}  id        — UUID
 * @property {string}  title     — Short description
 * @property {boolean} completed — Whether this subtask is done
 */

/**
 * @typedef {Object} Task
 * @property {string}   id               — UUID
 * @property {string}   title            — Task title
 * @property {string}   description      — Detailed description
 * @property {string}   deadline         — ISO-8601 date string
 * @property {string}   category         — One of CONFIG.TASK_CATEGORIES
 * @property {number}   priority         — One of CONFIG.PRIORITY_LEVELS values
 * @property {'pending'|'in-progress'|'completed'} status
 * @property {Subtask[]} subtasks        — Ordered list of subtasks
 * @property {number}   estimatedMinutes — Estimated effort
 * @property {string}   createdAt        — ISO-8601 timestamp
 * @property {string|null} completedAt   — ISO-8601 timestamp or null
 * @property {number}   riskScore        — 0 – 1 float
 * @property {string}   aiNotes          — Notes generated by Gemini
 */

/**
 * Return the full list of tasks.
 * @returns {Task[]}
 */
export function getTasks() {
  return get('tasks', []);
}

/**
 * Overwrite the entire task list.
 * @param {Task[]} tasks
 */
export function saveTasks(tasks) {
  set('tasks', tasks);
}

/**
 * Append a new task, auto-generating an id and createdAt timestamp.
 * @param {Partial<Task>} taskData — Task fields (id & createdAt are set automatically)
 * @returns {Task} The fully-formed task that was saved
 */
export function addTask(taskData) {
  const tasks = getTasks();

  /** @type {Task} */
  const task = {
    id: generateId(),
    title: taskData.title || 'Untitled Task',
    description: taskData.description || '',
    deadline: taskData.deadline || null,
    category: taskData.category || 'Personal',
    priority: taskData.priority ?? CONFIG.PRIORITY_LEVELS.MEDIUM,
    status: taskData.status || 'pending',
    subtasks: taskData.subtasks || [],
    estimatedMinutes: taskData.estimatedMinutes || 0,
    createdAt: new Date().toISOString(),
    completedAt: null,
    riskScore: taskData.riskScore ?? 0,
    aiNotes: taskData.aiNotes || ''
  };

  tasks.push(task);
  saveTasks(tasks);
  return task;
}

/**
 * Merge partial updates into an existing task.
 * @param {string} id — Task UUID
 * @param {Partial<Task>} updates — Fields to overwrite
 * @returns {Task|null} The updated task, or null if not found
 */
export function updateTask(id, updates) {
  const tasks = getTasks();
  const index = tasks.findIndex((t) => t.id === id);
  if (index === -1) return null;

  // If marking completed, stamp the time
  if (updates.status === 'completed' && tasks[index].status !== 'completed') {
    updates.completedAt = new Date().toISOString();
  }

  tasks[index] = { ...tasks[index], ...updates };
  saveTasks(tasks);
  return tasks[index];
}

/**
 * Delete a task by id.
 * @param {string} id — Task UUID
 * @returns {boolean} true if removed, false if not found
 */
export function deleteTask(id) {
  const tasks = getTasks();
  const filtered = tasks.filter((t) => t.id !== id);
  if (filtered.length === tasks.length) return false;
  saveTasks(filtered);
  return true;
}

// ── Chat history ───────────────────────────────────────────────────────

/**
 * @typedef {Object} ChatMessage
 * @property {string} role      — "user" | "assistant"
 * @property {string} content   — Message text
 * @property {string} timestamp — ISO-8601
 */

/**
 * Return stored chat messages.
 * @returns {ChatMessage[]}
 */
export function getChatHistory() {
  return get('chat_history', []);
}

/**
 * Replace the full chat history, trimming to MAX_CHAT_HISTORY.
 * @param {ChatMessage[]} messages
 */
export function saveChatHistory(messages) {
  const trimmed = messages.slice(-CONFIG.MAX_CHAT_HISTORY);
  set('chat_history', trimmed);
}

/**
 * Wipe all chat messages.
 */
export function clearChatHistory() {
  remove('chat_history');
}

// ── Settings ───────────────────────────────────────────────────────────

/**
 * @typedef {Object} AppSettings
 * @property {string}  theme           — 'dark' | 'light'
 * @property {string}  geminiApiKey    — User's Gemini API key
 * @property {boolean} notificationsOn — Desktop notifications enabled
 * @property {number}  pomodoroWork    — Override for work interval (seconds)
 * @property {number}  pomodoroBreak   — Override for break interval (seconds)
 */

/** Default settings applied on first launch. */
const DEFAULT_SETTINGS = {
  theme: 'dark',
  geminiApiKey: '',
  notificationsOn: true,
  pomodoroWork: CONFIG.POMODORO_WORK,
  pomodoroBreak: CONFIG.POMODORO_BREAK
};

/**
 * Return current settings, merged with defaults.
 * @returns {AppSettings}
 */
export function getSettings() {
  return { ...DEFAULT_SETTINGS, ...get('settings', {}) };
}

/**
 * Merge partial updates into persisted settings.
 * @param {Partial<AppSettings>} updates
 */
export function saveSettings(updates) {
  const current = getSettings();
  set('settings', { ...current, ...updates });
}

// ── Stats / analytics ─────────────────────────────────────────────────

/**
 * @typedef {Object} AppStats
 * @property {number} tasksCreated    — Lifetime count
 * @property {number} tasksCompleted  — Lifetime count
 * @property {number} pomodorosDone   — Lifetime count
 * @property {number} totalFocusMin   — Total focus minutes
 * @property {number} chatMessages    — Lifetime count
 * @property {string} lastActiveDate  — ISO-8601 date string
 */

/** Default stats for a brand-new user. */
const DEFAULT_STATS = {
  tasksCreated: 0,
  tasksCompleted: 0,
  pomodorosDone: 0,
  totalFocusMin: 0,
  chatMessages: 0,
  lastActiveDate: new Date().toISOString()
};

/**
 * Return current stats, merged with defaults.
 * @returns {AppStats}
 */
export function getStats() {
  return { ...DEFAULT_STATS, ...get('stats', {}) };
}

/**
 * Merge partial updates into persisted stats.
 * @param {Partial<AppStats>} updates
 */
export function updateStats(updates) {
  const current = getStats();
  set('stats', { ...current, ...updates });
}
